App\Entities\Resource:
  type: entity
  table: resourse
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    links:
      type: simple_array
    generate:
      type: string
    name:
      type: string
    description:
      type: string
    sum:
      type: integer
  oneToMany:
    accesses:
      targetEntity: App\Entities\Access
      mappedBy: resource
